# Generated by Django 6.0.1 on 2026-01-30 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('issue', 'user')},
        ),
    ]
