# Generated by Django 6.0.1 on 2026-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_rename_create_at_vote_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'UpVote'), (-1, 'DownVote'), (0, 'No options')], default=0),
        ),
    ]
