# Generated by Django 6.0.1 on 2026-02-05 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0005_alter_issue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('environmental', 'Environmental Development'), ('public_service', 'Public Service Request'), ('community', 'Community Announcement'), ('system', 'System Notification')], default='system', max_length=50)),
                ('event_type', models.CharField(choices=[('citizen_issue_reported', 'Issue Reported'), ('citizen_issue_accepted', 'Issue Accepted'), ('citizen_issue_in_progress', 'Issue In Progress'), ('citizen_issue_resolved', 'Issue Resolved'), ('citizen_comment_added', 'Comment Added'), ('citizen_survey_request', 'Survey Request'), ('authority_new_assignment', 'New Assignment'), ('authority_escalation', 'Issue Escalated'), ('authority_deadline_warning', 'Deadline Warning'), ('authority_performance_alert', 'Performance Alert'), ('community_announcement', 'Community Announcement'), ('community_event', 'Community Event'), ('volunteer_opportunity', 'Volunteer Opportunity'), ('welcome_message', 'Welcome Message'), ('account_verified', 'Account Verified'), ('weekly_summary', 'Weekly Summary')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_area', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency_level', models.IntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('requires_response', models.BooleanField(default=False)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_provided', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='issues.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['user', 'category'], name='notificatio_user_id_4652f6_idx'), models.Index(fields=['ward_area', 'created_at'], name='notificatio_ward_ar_b98354_idx')],
            },
        ),
    ]
