# Generated by Django 6.0.1 on 2026-02-05 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_8a7c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_4652f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_ward_ar_b98354_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='expires_at',
            new_name='read_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ref_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('citizen_issue_reported', 'Issue Reported'), ('citizen_issue_resolved', 'Issue Resolved')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='department',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='feedback_provided',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_acknowledged',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='requires_response',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='response_deadline',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='satisfaction_rating',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='urgency_level',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ward_area',
        ),
    ]
